# Generated by Django 4.2.1 on 2023-05-12 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('cedulaCiudadania', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('lastName', models.TextField()),
                ('birthday', models.DateField()),
                ('gender', models.TextField()),
                ('cedulaCiudadania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.login')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('images', models.TextField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.login', to_field='user')),
            ],
        ),
    ]
